### ISSUE TITLE
Suggestion: Keep jQuery in the head

### ISSUE THREAD

**Issue by wpexplorer** [joshuadavidnelson/scripts-to-footer#2]
Would be great to keep jQuery in the head because a lot of 3rd party plugins add inline js in the header which then causes the "jQuery undefined" error.

Besides that, nice little plugin, thanks for sharing ;) Will definitely recommend!

**Comment by joshuadavidnelson** [comment]
Great, idea, however...

I think it might be an issue because the plugin is set to remove the default script hooks in the header, and then WordPress spits everything out in the footer instead. In order to single out a specific script you have to un-enqueue it, which would be an issue for jquery - if it's not queued then WordPress won't enqueue any dependent scripts. If we place a second jquery callout in the header we'd run into issues with conflicts as well. I'll try to do some research/testing on potential other methods when I have time, though.

Part of the next release (whenever I finally have time to finish it!) will be to have an settings page - so users can globally set to turn the functionality on/off, and then they will have (and already have) the option to override that on specific pages. I'll see about adding this option to that settings page as well...

**Comment by wpexplorer** [comment]
Hum, yes I didn't really look to see how you were doing things ;)

clean_head runs on the default priority (10) so dequeuing and enqueuing jQuery at a later priority could work no? Since jQuery will be in the header it will always run before all other scripts since those will be in the footer.

Another option may be to use $wp_scripts to loop through all scripts (excerpt core scripts such as jQuery, jQuery UI and jQuery migrate)? Not sure if it's possible though.

```
global $wp_scripts;
if ( ! ( $wp_scripts instanceof WP_Scripts ) ) {
    $wp_scripts = new WP_Scripts();
}
print_r( $wp_scripts );
```

Just some thoughts. I forked the plugin so I will mess with it for my own needs and you are more then welcome to have a look when I do so ;)

**Comment by joshuadavidnelson** [comment]
Yea, I've tried playing around with other methods of moving scripts to the footer that would allow me to pick and choose, but because scripts can be enqueued anywhere, it's difficult to be thorough. The simplicity of the plugin right now is that everything gets dumped. 

Let me know if you figure something out, happy to accept pull requests!

**Comment by wpexplorer** [comment]
Definitely. I just moved to a new house and my office is finally all setup so I need to catch up on some things and then I want to work on this a bit so I can use it on my theme demos and increase by Google Analytics score a bit (just because a lot of potential customers/users actually look at that).

Basically I would assume setting your priority for the action hook to something insane like 99999 should capture all scripts.

**Comment by joshuadavidnelson** [comment]
Ok, sounds good. This approach could work, but it would be a complete re-write of the plugin.

I'd be open to expanding the settings to allow both options - the "broad-stroke" approach that is currently used, and the manual approach that allows singling out of scripts (with some options to keep default scripts in the header). The harder part is creating a list for options on the back end - because each page/post could potentially have a different list of scripts. I think it would have to be a bit more general for a settings page (like "keep jquery in the header" or "keep all WP default scripts in the header"). It could quickly unravel into a complex issue if it was more specific.

One of my to-dos is to build a settings page with a global "on/off" option as well, so this could be added to the settings page. Doing it that way and having the broad-stroke be default will make it a bit more backwards compatible as well.

**Comment by wpexplorer** [comment]
Definitely. I was planning on re-writing it for my use so I won't fork it - but I'll let you know when I do it, so you can have a look at what I did and see if you want to take some ideas from it. I was going to remove the meta options also because I don't see any circumstance where I would need that and instead just add a filter hook.

**Comment by joshuadavidnelson** [comment]
Cool, appreciate keeping me in the loop!

**Comment by jasperf** [comment]
Yeah to be able to allow some scripts and for sure jQuery to stay without adding a specific snippet like https://gist.github.com/joshuadavidnelson/8543278 would be great. I do not think there is a plugin that does that atm. I guess that is because it would be quite a bit of work.

**Comment by joshuadavidnelson** [comment]
I'm working on a few updates to allow for better use of disabling the plugin (specifically for pages like home, archive, etc that don't have an ID), the development branch has been updated to where I am at the moment, though nothing is thoroughly tested or set in stone yet. Take a look if you're interested. More to come soon, I hope!

**Comment by joshuadavidnelson** [comment]
In regards to pulling jquery out, it seems like one approach would be to find a way to trick WordPress into thinking you've already run a script (I'm still looking through the wp-scripts class and files), then you could manually place it in the header, tell WP it's been deployed, and allow STF to remove the header hooks like it does (forcing all other scripts, include - and this is key - any dependents of jquery). The downside of the current method is that you have to manually place any jquery dependents back into the header/footer.

Alternatively, I've played around with the idea of forcing the $in_footer argument on all scripts, but there's no clear way to institute this with WP's current hooks/filters that I can see, and it would have to be done at a very late priority to insure nothing was missed.

**Comment by joshuadavidnelson** [comment]
Ok, so 27b2e3f is a potential work around, however it ends up printing whatever script you want to keep in the header as well as it's dependents. So, anything dependent on jquery would be printed with it, which is not ideal for many cases.

Filter works like this:

``` php
add_filter( 'stf_exclude_scripts', 'jdn_header_scripts', 10, 1 );
function jdn_header_scripts( $scripts ) {
    $scripts[] = 'jquery';
    return $scripts;
}
```

**Note:** This is on the development branch and is still in-process, but I'd appreciate any other eyes on it.

**Comment by joshuadavidnelson** [comment]
Actually, this appears to work quite well, so I'm going to run with it. I'm also going to add a checkbox on the settings page to keep jQuery in the header by default (per @jasperf's request).

**Comment by joshuadavidnelson** [comment]
@jasperf See b5ac2bb398e9bc9cee4d2f88f638ea918288bbc7 for a built-in option to keep jquery in the header section. I've got to do more testing on the new version, and I want to make sure everything is good on multi-site, before pushing it to the WP.org repo.

**Comment by jasperf** [comment]
Will check myself this weekend or tomorrow. Thanks for all the work so far!

**Comment by joshuadavidnelson** [comment]
Draft documentation update: https://gist.github.com/joshuadavidnelson/1be879bbb3ac7b89dc0a, for reference.

**Comment by joshuadavidnelson** [comment]
See Version 0.6.0 3a7cac3e33ee8a5f7e65662d4701cf54326ee00f

**Comment by wpexplorer** [comment]
Wow, I totally forgot about this - sorry live got a bit crazy. Thanks so much for all your work. I am eager to test things out ;)

**Comment by joshuadavidnelson** [comment]
Hey, no worries! This version is live now and has received some good feedback from uses so far. Let me know if you have any questions, suggestions, et cetera!
